--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_chordcounter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_chordcounter (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    sub_tasks text NOT NULL,
    count integer NOT NULL,
    CONSTRAINT django_celery_results_chordcounter_count_check CHECK ((count >= 0))
);


ALTER TABLE public.django_celery_results_chordcounter OWNER TO postgres;

--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_chordcounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_chordcounter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_groupresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_groupresult (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_done timestamp with time zone NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text
);


ALTER TABLE public.django_celery_results_groupresult OWNER TO postgres;

--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_groupresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_groupresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_taskresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_taskresult (
    id integer NOT NULL,
    task_id character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text,
    date_done timestamp with time zone NOT NULL,
    traceback text,
    meta text,
    task_args text,
    task_kwargs text,
    task_name character varying(255),
    worker character varying(100),
    date_created timestamp with time zone NOT NULL,
    periodic_task_name character varying(255),
    date_started timestamp with time zone
);


ALTER TABLE public.django_celery_results_taskresult OWNER TO postgres;

--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_taskresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_taskresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: trafficapp_alertlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_alertlog (
    id bigint NOT NULL,
    scenario character varying(150),
    direction character varying(64),
    vehicle_class character varying(128),
    "timestamp" timestamp with time zone NOT NULL,
    details jsonb NOT NULL,
    sent_emails text NOT NULL,
    webhook_status character varying(256) NOT NULL,
    rule_id bigint
);


ALTER TABLE public.trafficapp_alertlog OWNER TO postgres;

--
-- Name: trafficapp_alertlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_alertlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_alertlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trafficapp_alertrule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_alertrule (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    active boolean NOT NULL,
    scenarios jsonb NOT NULL,
    directions jsonb NOT NULL,
    vehicle_classes jsonb NOT NULL,
    rule_type character varying(32) NOT NULL,
    threshold double precision NOT NULL,
    sustained_minutes integer NOT NULL,
    webhook_url character varying(200),
    emails text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    cooldown_seconds integer NOT NULL,
    created_by_id integer
);


ALTER TABLE public.trafficapp_alertrule OWNER TO postgres;

--
-- Name: trafficapp_alertrule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_alertrule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_alertrule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trafficapp_intersection; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_intersection (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.trafficapp_intersection OWNER TO postgres;

--
-- Name: trafficapp_intersection_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_intersection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_intersection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trafficapp_scenario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_scenario (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.trafficapp_scenario OWNER TO postgres;

--
-- Name: trafficapp_scenario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_scenario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_scenario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trafficapp_vehicleclass; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_vehicleclass (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.trafficapp_vehicleclass OWNER TO postgres;

--
-- Name: trafficapp_vehicleclass_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_vehicleclass ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_vehicleclass_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trafficapp_vehiclecount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_vehiclecount (
    id bigint NOT NULL,
    direction character varying(50) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    count integer NOT NULL,
    scenario character varying(50) NOT NULL,
    intersection_id bigint NOT NULL,
    vehicle_class_id bigint NOT NULL,
    CONSTRAINT trafficapp_vehiclecount_count_check CHECK ((count >= 0))
);


ALTER TABLE public.trafficapp_vehiclecount OWNER TO postgres;

--
-- Name: trafficapp_vehiclecount_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_vehiclecount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_vehiclecount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trafficapp_videosource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trafficapp_videosource (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    path character varying(200) NOT NULL,
    scenario_id bigint NOT NULL
);


ALTER TABLE public.trafficapp_videosource OWNER TO postgres;

--
-- Name: trafficapp_videosource_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trafficapp_videosource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trafficapp_videosource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add scenario	7	add_scenario
26	Can change scenario	7	change_scenario
27	Can delete scenario	7	delete_scenario
28	Can view scenario	7	view_scenario
29	Can add video source	8	add_videosource
30	Can change video source	8	change_videosource
31	Can delete video source	8	delete_videosource
32	Can view video source	8	view_videosource
33	Can add vehicle class	9	add_vehicleclass
34	Can change vehicle class	9	change_vehicleclass
35	Can delete vehicle class	9	delete_vehicleclass
36	Can view vehicle class	9	view_vehicleclass
37	Can add intersection	10	add_intersection
38	Can change intersection	10	change_intersection
39	Can delete intersection	10	delete_intersection
40	Can view intersection	10	view_intersection
41	Can add vehicle count	11	add_vehiclecount
42	Can change vehicle count	11	change_vehiclecount
43	Can delete vehicle count	11	delete_vehiclecount
44	Can view vehicle count	11	view_vehiclecount
45	Can add alert rule	12	add_alertrule
46	Can change alert rule	12	change_alertrule
47	Can delete alert rule	12	delete_alertrule
48	Can view alert rule	12	view_alertrule
49	Can add alert log	13	add_alertlog
50	Can change alert log	13	change_alertlog
51	Can delete alert log	13	delete_alertlog
52	Can view alert log	13	view_alertlog
53	Can add crontab	14	add_crontabschedule
54	Can change crontab	14	change_crontabschedule
55	Can delete crontab	14	delete_crontabschedule
56	Can view crontab	14	view_crontabschedule
57	Can add interval	15	add_intervalschedule
58	Can change interval	15	change_intervalschedule
59	Can delete interval	15	delete_intervalschedule
60	Can view interval	15	view_intervalschedule
61	Can add periodic task	16	add_periodictask
62	Can change periodic task	16	change_periodictask
63	Can delete periodic task	16	delete_periodictask
64	Can view periodic task	16	view_periodictask
65	Can add periodic task track	17	add_periodictasks
66	Can change periodic task track	17	change_periodictasks
67	Can delete periodic task track	17	delete_periodictasks
68	Can view periodic task track	17	view_periodictasks
69	Can add solar event	18	add_solarschedule
70	Can change solar event	18	change_solarschedule
71	Can delete solar event	18	delete_solarschedule
72	Can view solar event	18	view_solarschedule
73	Can add clocked	19	add_clockedschedule
74	Can change clocked	19	change_clockedschedule
75	Can delete clocked	19	delete_clockedschedule
76	Can view clocked	19	view_clockedschedule
77	Can add task result	20	add_taskresult
78	Can change task result	20	change_taskresult
79	Can delete task result	20	delete_taskresult
80	Can view task result	20	view_taskresult
81	Can add chord counter	21	add_chordcounter
82	Can change chord counter	21	change_chordcounter
83	Can delete chord counter	21	delete_chordcounter
84	Can view chord counter	21	view_chordcounter
85	Can add group result	22	add_groupresult
86	Can change group result	22	change_groupresult
87	Can delete group result	22	delete_groupresult
88	Can view group result	22	view_groupresult
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1000000$8VYG1mMTXxpumvzqcPK083$ZjqGrkJ73Z/ug4ftl1GKE4auZR8/Fjjx7teP1WRyfUc=	\N	f	user1			a@b.com	f	t	2025-06-22 20:13:03.416017+05:45
3	pbkdf2_sha256$1000000$f84rzH3HMAdQsyvEorWrgv$RbeNuIOeemeCtrscbdptmC2U4vwmc38eWssCkDjVFOo=	\N	t	admin1			admin1@example.com	t	t	2025-06-22 20:21:03.603889+05:45
4	pbkdf2_sha256$1000000$olIzZrmm8xrVzE0mlRIj7c$GsrUph2FKIHmLLmonUo/UEIpaPLStsJenlZIun4Gc/Y=	\N	f	user2			user2@example.com	f	t	2025-06-22 20:21:31.473239+05:45
5	pbkdf2_sha256$1000000$AhKacnq1KB4UTyF0LUyGp1$gMoRfuwYyzN4Bx37ghqkqi4HLyO9B14u2LgUn9KAZ/s=	\N	f	Ranjesh			Ranjesh@gmail.com	f	t	2025-06-23 12:00:43.752845+05:45
6	pbkdf2_sha256$1000000$FdzkDeNCQ1PBFsx2IE5WVw$X0nU16/F0xqon1jKgLZkfIw1F72JJcDSlq3iF5Mltmk=	\N	f	Test			Test@gmail.com	f	t	2025-06-23 12:07:03.84696+05:45
7	pbkdf2_sha256$1000000$biSD0pkw6elCjb2I8Af5F5$6GR9/l78e7pOtgnwxLTGQhwBS7Yj14myTMS6UcWd7Io=	\N	f	Panda			Panda@gmail.com	f	t	2025-06-23 12:38:47.166056+05:45
8	pbkdf2_sha256$1000000$JanOpMvLXqhKqs94H8Dl9n$ksMlEjs7a/ex1KnPcPpXVyFlDkO5EGacP03uedB2DLI=	\N	f	Ratik			Ratik@gmail.com	f	t	2025-06-23 21:25:23.281712+05:45
9	pbkdf2_sha256$1000000$KoWtvmpjb38Csx72S7gCmo$3TBM8ER3UhF6ma6ytkKNxweWex2Z+k1BgnmD6qksAvM=	\N	f	Pamda			Pamda@gmail.com	f	t	2025-06-24 15:39:11.869519+05:45
1	pbkdf2_sha256$1000000$9Fe1JN5QDH3yqbRjIdD0E3$hE53IqGfaiz2+181q0YV2Pysyciy0P1+eTh2opRoaoo=	2025-06-26 10:20:36.041702+05:45	t	admin			admin@gmail.com	t	t	2025-06-04 20:02:54.014716+05:45
10	pbkdf2_sha256$1000000$jpZksjP4Ie4YVVEiWKKy6r$PCZhnmPGpyrtxMSdMWkq0bLhfAq9ZkMQIK6cwZKzqis=	\N	f	Disco			Disco@gmail.com	f	t	2025-06-26 10:21:38.14615+05:45
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-06-08 15:48:57.273351+05:45	1	intersection4	1	[{"added": {}}]	10	1
2	2025-06-08 15:49:04.746413+05:45	1	intersection4	2	[]	10	1
3	2025-06-08 15:50:17.97143+05:45	1	intersection4	1	[{"added": {}}]	7	1
4	2025-06-08 15:50:55.084692+05:45	1	IntersectionCam (intersection4)	1	[{"added": {}}]	8	1
5	2025-06-08 16:55:40.080732+05:45	37	MainStreet | mini_truck | Godawari | 1970-01-01 00:01	3		11	1
6	2025-06-08 16:55:40.080778+05:45	36	MainStreet | ambulance | Kalanki | 1970-01-01 00:01	3		11	1
7	2025-06-08 16:55:40.080799+05:45	35	MainStreet | micro_bus | Lagankhel | 1970-01-01 00:01	3		11	1
8	2025-06-08 16:55:40.080815+05:45	34	MainStreet | micro_bus | Kalanki | 1970-01-01 00:01	3		11	1
9	2025-06-08 16:55:40.080831+05:45	33	MainStreet | scooter | Godawari | 1970-01-01 00:01	3		11	1
10	2025-06-08 16:55:40.080846+05:45	32	MainStreet | scooter | Lagankhel | 1970-01-01 00:01	3		11	1
11	2025-06-08 16:55:40.08086+05:45	31	MainStreet | scooter | Kalanki | 1970-01-01 00:01	3		11	1
12	2025-06-08 16:55:40.080873+05:45	30	MainStreet | transport_vehicle | Kalanki | 1970-01-01 00:01	3		11	1
13	2025-06-08 16:55:40.080886+05:45	29	MainStreet | bike | Godawari | 1970-01-01 00:01	3		11	1
14	2025-06-08 16:55:40.0809+05:45	28	MainStreet | bike | Lagankhel | 1970-01-01 00:01	3		11	1
15	2025-06-08 16:55:40.080913+05:45	27	MainStreet | bike | Kalanki | 1970-01-01 00:01	3		11	1
16	2025-06-08 16:55:40.080926+05:45	26	MainStreet | SUV | Lagankhel | 1970-01-01 00:01	3		11	1
17	2025-06-08 16:55:40.080938+05:45	25	MainStreet | SUV | Kalanki | 1970-01-01 00:01	3		11	1
18	2025-06-08 16:55:40.08095+05:45	24	MainStreet | car | Lagankhel | 1970-01-01 00:01	3		11	1
19	2025-06-08 16:55:40.080967+05:45	23	MainStreet | car | Kalanki | 1970-01-01 00:01	3		11	1
20	2025-06-08 16:55:40.08098+05:45	22	MainStreet | van | Lagankhel | 1970-01-01 00:01	3		11	1
21	2025-06-08 16:55:40.080992+05:45	21	MainStreet | van | Kalanki | 1970-01-01 00:01	3		11	1
22	2025-06-08 16:55:40.081005+05:45	20	MainStreet | taxi | Lagankhel | 1970-01-01 00:01	3		11	1
23	2025-06-08 16:55:40.081017+05:45	19	MainStreet | taxi | Kalanki | 1970-01-01 00:01	3		11	1
24	2025-06-08 16:55:40.081028+05:45	18	MainStreet | truck | Kalanki | 1970-01-01 00:01	3		11	1
25	2025-06-08 16:55:40.081052+05:45	17	MainStreet | bus | Lagankhel | 1970-01-01 00:01	3		11	1
26	2025-06-08 16:55:40.081067+05:45	16	MainStreet | bus | Kalanki | 1970-01-01 00:01	3		11	1
27	2025-06-08 16:55:40.081079+05:45	15	MainStreet | micro_bus | Kalanki | 1970-01-01 00:00	3		11	1
28	2025-06-08 16:55:40.081092+05:45	14	MainStreet | transport_vehicle | Kalanki | 1970-01-01 00:00	3		11	1
29	2025-06-08 16:55:40.081104+05:45	13	MainStreet | ambulance | Kalanki | 1970-01-01 00:00	3		11	1
30	2025-06-08 16:55:40.081117+05:45	12	MainStreet | SUV | Kalanki | 1970-01-01 00:00	3		11	1
31	2025-06-08 16:55:40.08113+05:45	11	MainStreet | bike | Lagankhel | 1970-01-01 00:00	3		11	1
32	2025-06-08 16:55:40.081143+05:45	10	MainStreet | bike | Kalanki | 1970-01-01 00:00	3		11	1
33	2025-06-08 16:55:40.081155+05:45	9	MainStreet | van | Kalanki | 1970-01-01 00:00	3		11	1
34	2025-06-08 16:55:40.081167+05:45	8	MainStreet | taxi | Lagankhel | 1970-01-01 00:00	3		11	1
35	2025-06-08 16:55:40.081181+05:45	7	MainStreet | taxi | Kalanki | 1970-01-01 00:00	3		11	1
36	2025-06-08 16:55:40.081193+05:45	6	MainStreet | scooter | Kalanki | 1970-01-01 00:00	3		11	1
37	2025-06-08 16:55:40.081205+05:45	5	MainStreet | truck | Kalanki | 1970-01-01 00:00	3		11	1
38	2025-06-08 16:55:40.081217+05:45	4	MainStreet | car | Lagankhel | 1970-01-01 00:00	3		11	1
39	2025-06-08 16:55:40.08123+05:45	3	MainStreet | car | Kalanki | 1970-01-01 00:00	3		11	1
40	2025-06-08 16:55:40.081243+05:45	2	MainStreet | bus | Lagankhel | 1970-01-01 00:00	3		11	1
41	2025-06-08 16:55:40.081256+05:45	1	MainStreet | bus | Kalanki | 1970-01-01 00:00	3		11	1
42	2025-06-08 16:55:40.082845+05:45	37	MainStreet | mini_truck | Godawari | 1970-01-01 00:01	3		11	1
43	2025-06-08 16:55:40.082886+05:45	36	MainStreet | ambulance | Kalanki | 1970-01-01 00:01	3		11	1
44	2025-06-08 16:55:40.08291+05:45	35	MainStreet | micro_bus | Lagankhel | 1970-01-01 00:01	3		11	1
45	2025-06-08 16:55:40.082933+05:45	34	MainStreet | micro_bus | Kalanki | 1970-01-01 00:01	3		11	1
46	2025-06-08 16:55:40.082954+05:45	33	MainStreet | scooter | Godawari | 1970-01-01 00:01	3		11	1
47	2025-06-08 16:55:40.082971+05:45	32	MainStreet | scooter | Lagankhel | 1970-01-01 00:01	3		11	1
48	2025-06-08 16:55:40.082985+05:45	31	MainStreet | scooter | Kalanki | 1970-01-01 00:01	3		11	1
49	2025-06-08 16:55:40.082998+05:45	30	MainStreet | transport_vehicle | Kalanki | 1970-01-01 00:01	3		11	1
50	2025-06-08 16:55:40.083011+05:45	29	MainStreet | bike | Godawari | 1970-01-01 00:01	3		11	1
51	2025-06-08 16:55:40.083023+05:45	28	MainStreet | bike | Lagankhel | 1970-01-01 00:01	3		11	1
52	2025-06-08 16:55:40.083035+05:45	27	MainStreet | bike | Kalanki | 1970-01-01 00:01	3		11	1
53	2025-06-08 16:55:40.083047+05:45	26	MainStreet | SUV | Lagankhel | 1970-01-01 00:01	3		11	1
54	2025-06-08 16:55:40.083059+05:45	25	MainStreet | SUV | Kalanki | 1970-01-01 00:01	3		11	1
55	2025-06-08 16:55:40.083071+05:45	24	MainStreet | car | Lagankhel | 1970-01-01 00:01	3		11	1
56	2025-06-08 16:55:40.083086+05:45	23	MainStreet | car | Kalanki | 1970-01-01 00:01	3		11	1
57	2025-06-08 16:55:40.083104+05:45	22	MainStreet | van | Lagankhel | 1970-01-01 00:01	3		11	1
58	2025-06-08 16:55:40.083117+05:45	21	MainStreet | van | Kalanki | 1970-01-01 00:01	3		11	1
59	2025-06-08 16:55:40.083129+05:45	20	MainStreet | taxi | Lagankhel | 1970-01-01 00:01	3		11	1
60	2025-06-08 16:55:40.083141+05:45	19	MainStreet | taxi | Kalanki | 1970-01-01 00:01	3		11	1
61	2025-06-08 16:55:40.083154+05:45	18	MainStreet | truck | Kalanki | 1970-01-01 00:01	3		11	1
62	2025-06-08 16:55:40.083168+05:45	17	MainStreet | bus | Lagankhel | 1970-01-01 00:01	3		11	1
63	2025-06-08 16:55:40.083186+05:45	16	MainStreet | bus | Kalanki | 1970-01-01 00:01	3		11	1
64	2025-06-08 16:55:40.083198+05:45	15	MainStreet | micro_bus | Kalanki | 1970-01-01 00:00	3		11	1
65	2025-06-08 16:55:40.083211+05:45	14	MainStreet | transport_vehicle | Kalanki | 1970-01-01 00:00	3		11	1
66	2025-06-08 16:55:40.083223+05:45	13	MainStreet | ambulance | Kalanki | 1970-01-01 00:00	3		11	1
67	2025-06-08 16:55:40.083236+05:45	12	MainStreet | SUV | Kalanki | 1970-01-01 00:00	3		11	1
68	2025-06-08 16:55:40.083248+05:45	11	MainStreet | bike | Lagankhel | 1970-01-01 00:00	3		11	1
69	2025-06-08 16:55:40.08326+05:45	10	MainStreet | bike | Kalanki | 1970-01-01 00:00	3		11	1
70	2025-06-08 16:55:40.083272+05:45	9	MainStreet | van | Kalanki | 1970-01-01 00:00	3		11	1
71	2025-06-08 16:55:40.083284+05:45	8	MainStreet | taxi | Lagankhel | 1970-01-01 00:00	3		11	1
72	2025-06-08 16:55:40.083296+05:45	7	MainStreet | taxi | Kalanki | 1970-01-01 00:00	3		11	1
73	2025-06-08 16:55:40.083308+05:45	6	MainStreet | scooter | Kalanki | 1970-01-01 00:00	3		11	1
74	2025-06-08 16:55:40.083334+05:45	5	MainStreet | truck | Kalanki | 1970-01-01 00:00	3		11	1
75	2025-06-08 16:55:40.083349+05:45	4	MainStreet | car | Lagankhel | 1970-01-01 00:00	3		11	1
76	2025-06-08 16:55:40.083361+05:45	3	MainStreet | car | Kalanki | 1970-01-01 00:00	3		11	1
77	2025-06-08 16:55:40.083373+05:45	2	MainStreet | bus | Lagankhel | 1970-01-01 00:00	3		11	1
78	2025-06-08 16:55:40.083384+05:45	1	MainStreet | bus | Kalanki | 1970-01-01 00:00	3		11	1
79	2025-06-13 07:13:39.584858+05:45	2	MainStreet	2	[]	10	1
80	2025-06-13 07:15:40.562807+05:45	1	intersection4	2	[]	10	1
81	2025-06-13 07:19:09.12424+05:45	53	MainStreet | SUV | Lagankhel | 2025-06-13 01:33	1	[{"added": {}}]	11	1
82	2025-06-13 07:20:32.791319+05:45	53	MainStreet | SUV | Lagankhel | 2025-06-13 01:33	3		11	1
83	2025-06-13 07:20:32.791382+05:45	52	MainStreet | micro_bus | Kalanki | 1970-01-01 00:00	3		11	1
84	2025-06-13 07:20:32.791412+05:45	51	MainStreet | transport_vehicle | Kalanki | 1970-01-01 00:00	3		11	1
85	2025-06-13 07:20:32.791435+05:45	50	MainStreet | ambulance | Kalanki | 1970-01-01 00:00	3		11	1
86	2025-06-13 07:20:32.791458+05:45	49	MainStreet | SUV | Kalanki | 1970-01-01 00:00	3		11	1
87	2025-06-13 07:20:32.791473+05:45	48	MainStreet | bike | Lagankhel | 1970-01-01 00:00	3		11	1
88	2025-06-13 07:20:32.791489+05:45	47	MainStreet | bike | Kalanki | 1970-01-01 00:00	3		11	1
89	2025-06-13 07:20:32.791509+05:45	46	MainStreet | van | Kalanki | 1970-01-01 00:00	3		11	1
90	2025-06-13 07:20:32.791527+05:45	45	MainStreet | taxi | Lagankhel | 1970-01-01 00:00	3		11	1
91	2025-06-13 07:20:32.791541+05:45	44	MainStreet | taxi | Kalanki | 1970-01-01 00:00	3		11	1
92	2025-06-13 07:20:32.791554+05:45	43	MainStreet | scooter | Kalanki | 1970-01-01 00:00	3		11	1
93	2025-06-13 07:20:32.791567+05:45	42	MainStreet | truck | Kalanki | 1970-01-01 00:00	3		11	1
94	2025-06-13 07:20:32.791583+05:45	41	MainStreet | car | Lagankhel | 1970-01-01 00:00	3		11	1
95	2025-06-13 07:20:32.791603+05:45	40	MainStreet | car | Kalanki | 1970-01-01 00:00	3		11	1
96	2025-06-13 07:20:32.791629+05:45	39	MainStreet | bus | Lagankhel | 1970-01-01 00:00	3		11	1
97	2025-06-13 07:20:32.791643+05:45	38	MainStreet | bus | Kalanki | 1970-01-01 00:00	3		11	1
98	2025-06-13 07:24:15.212276+05:45	75	MainStreet | mini_truck | Godawari | 1970-01-01 00:01	3		11	1
99	2025-06-13 07:24:15.212359+05:45	73	MainStreet | micro_bus | Lagankhel | 1970-01-01 00:01	3		11	1
100	2025-06-13 07:24:15.212421+05:45	64	MainStreet | SUV | Lagankhel | 1970-01-01 00:01	3		11	1
101	2025-06-13 07:24:15.212452+05:45	71	MainStreet | scooter | Godawari | 1970-01-01 00:01	3		11	1
102	2025-06-13 07:24:15.21249+05:45	70	MainStreet | scooter | Lagankhel | 1970-01-01 00:01	3		11	1
103	2025-06-13 07:24:15.212519+05:45	66	MainStreet | bike | Lagankhel | 1970-01-01 00:01	3		11	1
104	2025-06-13 07:24:15.212551+05:45	68	MainStreet | transport_vehicle | Kalanki | 1970-01-01 00:01	3		11	1
105	2025-06-13 07:24:15.212585+05:45	67	MainStreet | bike | Godawari | 1970-01-01 00:01	3		11	1
106	2025-06-13 07:24:15.212615+05:45	72	MainStreet | micro_bus | Kalanki | 1970-01-01 00:01	3		11	1
107	2025-06-13 07:24:15.212646+05:45	63	MainStreet | SUV | Kalanki | 1970-01-01 00:01	3		11	1
108	2025-06-13 07:24:15.212674+05:45	62	MainStreet | car | Lagankhel | 1970-01-01 00:01	3		11	1
109	2025-06-13 07:24:15.212706+05:45	55	MainStreet | bus | Lagankhel | 1970-01-01 00:01	3		11	1
110	2025-06-13 07:24:15.212734+05:45	58	MainStreet | taxi | Lagankhel | 1970-01-01 00:01	3		11	1
111	2025-06-13 07:24:15.212764+05:45	74	MainStreet | ambulance | Kalanki | 1970-01-01 00:01	3		11	1
112	2025-06-13 07:24:15.212793+05:45	60	MainStreet | van | Lagankhel | 1970-01-01 00:01	3		11	1
113	2025-06-13 07:24:15.21282+05:45	59	MainStreet | van | Kalanki | 1970-01-01 00:01	3		11	1
114	2025-06-13 07:24:15.212847+05:45	65	MainStreet | bike | Kalanki | 1970-01-01 00:01	3		11	1
115	2025-06-13 07:24:15.212874+05:45	69	MainStreet | scooter | Kalanki | 1970-01-01 00:01	3		11	1
116	2025-06-13 07:24:15.212907+05:45	56	MainStreet | truck | Kalanki | 1970-01-01 00:01	3		11	1
117	2025-06-13 07:24:15.212962+05:45	57	MainStreet | taxi | Kalanki | 1970-01-01 00:01	3		11	1
118	2025-06-13 07:24:15.212995+05:45	61	MainStreet | car | Kalanki | 1970-01-01 00:01	3		11	1
119	2025-06-13 07:24:15.213024+05:45	54	MainStreet | bus | Kalanki | 1970-01-01 00:01	3		11	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_celery_results_chordcounter; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_results_chordcounter (id, group_id, sub_tasks, count) FROM stdin;
\.


--
-- Data for Name: django_celery_results_groupresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_results_groupresult (id, group_id, date_created, date_done, content_type, content_encoding, result) FROM stdin;
\.


--
-- Data for Name: django_celery_results_taskresult; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_celery_results_taskresult (id, task_id, status, content_type, content_encoding, result, date_done, traceback, meta, task_args, task_kwargs, task_name, worker, date_created, periodic_task_name, date_started) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	trafficapp	scenario
8	trafficapp	videosource
9	trafficapp	vehicleclass
10	trafficapp	intersection
11	trafficapp	vehiclecount
12	trafficapp	alertrule
13	trafficapp	alertlog
14	django_celery_beat	crontabschedule
15	django_celery_beat	intervalschedule
16	django_celery_beat	periodictask
17	django_celery_beat	periodictasks
18	django_celery_beat	solarschedule
19	django_celery_beat	clockedschedule
20	django_celery_results	taskresult
21	django_celery_results	chordcounter
22	django_celery_results	groupresult
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-06-04 18:48:16.758928+05:45
2	auth	0001_initial	2025-06-04 18:48:16.826007+05:45
3	admin	0001_initial	2025-06-04 18:48:16.845405+05:45
4	admin	0002_logentry_remove_auto_add	2025-06-04 18:48:16.852514+05:45
5	admin	0003_logentry_add_action_flag_choices	2025-06-04 18:48:16.861066+05:45
6	contenttypes	0002_remove_content_type_name	2025-06-04 18:48:16.880913+05:45
7	auth	0002_alter_permission_name_max_length	2025-06-04 18:48:16.888832+05:45
8	auth	0003_alter_user_email_max_length	2025-06-04 18:48:16.901042+05:45
9	auth	0004_alter_user_username_opts	2025-06-04 18:48:16.910308+05:45
10	auth	0005_alter_user_last_login_null	2025-06-04 18:48:16.920277+05:45
11	auth	0006_require_contenttypes_0002	2025-06-04 18:48:16.922168+05:45
12	auth	0007_alter_validators_add_error_messages	2025-06-04 18:48:16.930505+05:45
13	auth	0008_alter_user_username_max_length	2025-06-04 18:48:16.94358+05:45
14	auth	0009_alter_user_last_name_max_length	2025-06-04 18:48:16.953337+05:45
15	auth	0010_alter_group_name_max_length	2025-06-04 18:48:16.968859+05:45
16	auth	0011_update_proxy_permissions	2025-06-04 18:48:16.982313+05:45
17	auth	0012_alter_user_first_name_max_length	2025-06-04 18:48:16.995792+05:45
18	sessions	0001_initial	2025-06-04 18:48:17.012354+05:45
19	trafficapp	0001_initial	2025-06-04 20:02:16.944541+05:45
20	trafficapp	0002_alertrule_alertlog	2025-08-27 17:46:28.057062+05:45
21	django_celery_beat	0001_initial	2025-08-27 19:32:46.9011+05:45
22	django_celery_beat	0002_auto_20161118_0346	2025-08-27 19:32:46.914602+05:45
23	django_celery_beat	0003_auto_20161209_0049	2025-08-27 19:32:46.92439+05:45
24	django_celery_beat	0004_auto_20170221_0000	2025-08-27 19:32:46.930907+05:45
25	django_celery_beat	0005_add_solarschedule_events_choices	2025-08-27 19:32:46.938004+05:45
26	django_celery_beat	0006_auto_20180322_0932	2025-08-27 19:32:46.98602+05:45
27	django_celery_beat	0007_auto_20180521_0826	2025-08-27 19:32:47.000972+05:45
28	django_celery_beat	0008_auto_20180914_1922	2025-08-27 19:32:47.040043+05:45
29	django_celery_beat	0006_auto_20180210_1226	2025-08-27 19:32:47.06113+05:45
30	django_celery_beat	0006_periodictask_priority	2025-08-27 19:32:47.070615+05:45
31	django_celery_beat	0009_periodictask_headers	2025-08-27 19:32:47.085828+05:45
32	django_celery_beat	0010_auto_20190429_0326	2025-08-27 19:32:47.267966+05:45
33	django_celery_beat	0011_auto_20190508_0153	2025-08-27 19:32:47.290492+05:45
34	django_celery_beat	0012_periodictask_expire_seconds	2025-08-27 19:32:47.308033+05:45
35	django_celery_beat	0013_auto_20200609_0727	2025-08-27 19:32:47.327398+05:45
36	django_celery_beat	0014_remove_clockedschedule_enabled	2025-08-27 19:32:47.338968+05:45
37	django_celery_beat	0015_edit_solarschedule_events_choices	2025-08-27 19:32:47.344084+05:45
38	django_celery_beat	0016_alter_crontabschedule_timezone	2025-08-27 19:32:47.357872+05:45
39	django_celery_beat	0017_alter_crontabschedule_month_of_year	2025-08-27 19:32:47.369628+05:45
40	django_celery_beat	0018_improve_crontab_helptext	2025-08-27 19:32:47.379597+05:45
41	django_celery_beat	0019_alter_periodictasks_options	2025-08-27 19:32:47.382131+05:45
42	django_celery_results	0001_initial	2025-08-27 19:32:47.394772+05:45
43	django_celery_results	0002_add_task_name_args_kwargs	2025-08-27 19:32:47.404487+05:45
44	django_celery_results	0003_auto_20181106_1101	2025-08-27 19:32:47.407586+05:45
45	django_celery_results	0004_auto_20190516_0412	2025-08-27 19:32:47.44231+05:45
46	django_celery_results	0005_taskresult_worker	2025-08-27 19:32:47.448748+05:45
47	django_celery_results	0006_taskresult_date_created	2025-08-27 19:32:47.480157+05:45
48	django_celery_results	0007_remove_taskresult_hidden	2025-08-27 19:32:47.487937+05:45
49	django_celery_results	0008_chordcounter	2025-08-27 19:32:47.505238+05:45
50	django_celery_results	0009_groupresult	2025-08-27 19:32:47.58906+05:45
51	django_celery_results	0010_remove_duplicate_indices	2025-08-27 19:32:47.595117+05:45
52	django_celery_results	0011_taskresult_periodic_task_name	2025-08-27 19:32:47.600409+05:45
53	django_celery_results	0012_taskresult_date_started	2025-08-27 19:32:47.606228+05:45
54	django_celery_results	0013_taskresult_django_cele_periodi_1993cf_idx	2025-08-27 19:32:47.611602+05:45
55	django_celery_results	0014_alter_taskresult_status	2025-08-27 19:32:47.618021+05:45
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
741lwrwzlh2pzqrt2mg2l9tdub0s1a2h	.eJxVjDsOwyAQBe9CHSH-gpTpcwa0u0BwEoFk7MrK3SMkF0n7ZuYdLMK-1biPvMYlsSuT7PK7IdArtwnSE9qjc-ptWxfkU-EnHfzeU37fTvfvoMKos6YkbNFksCCRxCCDKEkUgyoDklfoKBQwGbXUoLzPVjlPWgoia7xjny8jyjje:1uOCsC:TkTnYUWlinJlw0DzOgZHHEGjZbEW-NQyII_ScFlmQH0	2025-06-22 15:48:28.187348+05:45
x0ntzdshxizhg6l7hi4tj53i5ieqodwd	.eJxVjDsOwyAQBe9CHSH-gpTpcwa0u0BwEoFk7MrK3SMkF0n7ZuYdLMK-1biPvMYlsSuT7PK7IdArtwnSE9qjc-ptWxfkU-EnHfzeU37fTvfvoMKos6YkbNFksCCRxCCDKEkUgyoDklfoKBQwGbXUoLzPVjlPWgoia7xjny8jyjje:1uODpZ:5-AU-zrXpEMcVRTkuqT_7X9Xtzh6t5I9f1M1Mf7qmP0	2025-06-22 16:49:49.767147+05:45
kbmj34nqrq3ek8ulqj2heza8aw3cin57	.eJxVjDsOwyAQBe9CHSH-gpTpcwa0u0BwEoFk7MrK3SMkF0n7ZuYdLMK-1biPvMYlsSuT7PK7IdArtwnSE9qjc-ptWxfkU-EnHfzeU37fTvfvoMKos6YkbNFksCCRxCCDKEkUgyoDklfoKBQwGbXUoLzPVjlPWgoia7xjny8jyjje:1uUeKm:1yNGWY7tuRN3ARI-01gAWRU4zEY_F8BZWoX7c5cpr8A	2025-07-10 10:20:36.048083+05:45
\.


--
-- Data for Name: trafficapp_alertlog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_alertlog (id, scenario, direction, vehicle_class, "timestamp", details, sent_emails, webhook_status, rule_id) FROM stdin;
\.


--
-- Data for Name: trafficapp_alertrule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_alertrule (id, name, active, scenarios, directions, vehicle_classes, rule_type, threshold, sustained_minutes, webhook_url, emails, created_at, cooldown_seconds, created_by_id) FROM stdin;
\.


--
-- Data for Name: trafficapp_intersection; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_intersection (id, name) FROM stdin;
2	MainStreet
1	intersection4
3	myPhone
4	collegePhone
\.


--
-- Data for Name: trafficapp_scenario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_scenario (id, name) FROM stdin;
1	intersection4
\.


--
-- Data for Name: trafficapp_vehicleclass; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_vehicleclass (id, name) FROM stdin;
1	SUV
2	ambulance
3	auto_rickshaw
4	bike
5	bus
6	car
7	e-rickshaw
8	micro_bus
9	mini_truck
10	police_vehicle
11	school_bus
12	scooter
13	taxi
14	tempo
15	tractor
16	transport_vehicle
17	truck
18	van
\.


--
-- Data for Name: trafficapp_vehiclecount; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_vehiclecount (id, direction, "timestamp", count, scenario, intersection_id, vehicle_class_id) FROM stdin;
1	Kalanki	2025-06-24 11:57:00+05:45	19	intersection4	2	5
2	Lagankhel	2025-06-24 11:57:00+05:45	1	intersection4	2	5
3	Kalanki	2025-06-24 11:57:00+05:45	3	intersection4	2	6
4	Kalanki	2025-06-24 11:57:00+05:45	1	intersection4	2	17
5	Kalanki	2025-06-24 11:57:00+05:45	2	intersection4	2	12
6	Godawari	2025-06-24 11:57:00+05:45	1	intersection4	2	12
7	Kalanki	2025-06-24 11:57:00+05:45	5	intersection4	2	13
8	Kalanki	2025-06-24 11:57:00+05:45	3	intersection4	2	18
9	Kalanki	2025-06-24 11:57:00+05:45	1	intersection4	2	4
10	Godawari	2025-06-24 11:57:00+05:45	1	intersection4	2	4
11	Kalanki	2025-06-24 11:57:00+05:45	1	intersection4	2	1
12	Kalanki	2025-06-24 11:57:00+05:45	1	intersection4	2	2
13	Kalanki	2025-06-24 11:58:00+05:45	4	intersection4	2	13
14	Kalanki	2025-06-24 11:58:00+05:45	4	intersection4	2	1
15	Kalanki	2025-06-24 11:58:00+05:45	2	intersection4	2	6
16	Kalanki	2025-06-24 11:58:00+05:45	6	intersection4	2	18
17	Godawari	2025-06-24 11:58:00+05:45	1	intersection4	2	12
18	Kalanki	2025-06-24 11:58:00+05:45	18	intersection4	2	5
19	Lagankhel	2025-06-24 11:58:00+05:45	2	intersection4	2	5
20	Kalanki	2025-06-24 11:58:00+05:45	5	intersection4	2	17
21	Godawari	2025-06-24 11:58:00+05:45	1	intersection4	2	2
22	Kalanki	2025-06-24 11:59:00+05:45	9	intersection4	2	13
23	Kalanki	2025-06-24 11:59:00+05:45	3	intersection4	2	1
24	Kalanki	2025-06-24 11:59:00+05:45	10	intersection4	2	6
25	Kalanki	2025-06-24 11:59:00+05:45	31	intersection4	2	5
26	Kalanki	2025-06-24 11:59:00+05:45	2	intersection4	2	18
27	Kalanki	2025-06-24 11:59:00+05:45	5	intersection4	2	17
28	Kalanki	2025-06-24 11:59:00+05:45	1	intersection4	2	4
29	Kalanki	2025-06-24 12:00:00+05:45	7	intersection4	2	13
30	Kalanki	2025-06-24 12:00:00+05:45	3	intersection4	2	1
31	Kalanki	2025-06-24 12:00:00+05:45	9	intersection4	2	6
32	Kalanki	2025-06-24 12:00:00+05:45	29	intersection4	2	5
33	Kalanki	2025-06-24 12:00:00+05:45	2	intersection4	2	18
34	Kalanki	2025-06-24 12:00:00+05:45	7	intersection4	2	17
35	Kalanki	2025-06-24 12:00:00+05:45	2	intersection4	2	4
36	Kalanki	2025-06-24 12:01:00+05:45	6	intersection4	2	13
37	Kalanki	2025-06-24 12:01:00+05:45	3	intersection4	2	1
38	Kalanki	2025-06-24 12:01:00+05:45	7	intersection4	2	6
39	Kalanki	2025-06-24 12:01:00+05:45	24	intersection4	2	5
40	Kalanki	2025-06-24 12:01:00+05:45	3	intersection4	2	18
41	Kalanki	2025-06-24 12:01:00+05:45	5	intersection4	2	17
42	Kalanki	2025-06-24 12:01:00+05:45	1	intersection4	2	16
43	Kalanki	2025-06-24 12:01:00+05:45	1	intersection4	2	12
44	Kalanki	2025-06-24 12:01:00+05:45	3	intersection4	2	4
45	Kalanki	2025-06-24 12:02:00+05:45	9	intersection4	2	13
46	Kalanki	2025-06-24 12:02:00+05:45	3	intersection4	2	1
47	Kalanki	2025-06-24 12:02:00+05:45	9	intersection4	2	6
48	Kalanki	2025-06-24 12:02:00+05:45	22	intersection4	2	5
49	Kalanki	2025-06-24 12:02:00+05:45	5	intersection4	2	18
50	Kalanki	2025-06-24 12:02:00+05:45	5	intersection4	2	17
51	Kalanki	2025-06-24 12:02:00+05:45	4	intersection4	2	4
52	Lagankhel	2025-06-24 12:02:00+05:45	2	intersection4	2	4
53	Kalanki	2025-06-24 12:02:00+05:45	4	intersection4	2	12
54	Kalanki	2025-06-24 12:02:00+05:45	3	intersection4	2	8
55	Kalanki	2025-06-24 12:02:00+05:45	1	intersection4	2	2
56	Kalanki	2025-06-24 14:22:00+05:45	54	intersection4	2	5
57	Lagankhel	2025-06-24 14:22:00+05:45	2	intersection4	2	5
58	Kalanki	2025-06-24 14:22:00+05:45	9	intersection4	2	6
59	Kalanki	2025-06-24 14:22:00+05:45	8	intersection4	2	17
60	Kalanki	2025-06-24 14:22:00+05:45	2	intersection4	2	12
61	Godawari	2025-06-24 14:22:00+05:45	2	intersection4	2	12
62	Kalanki	2025-06-24 14:22:00+05:45	6	intersection4	2	13
63	Kalanki	2025-06-24 14:22:00+05:45	9	intersection4	2	18
64	Kalanki	2025-06-24 14:22:00+05:45	2	intersection4	2	4
65	Godawari	2025-06-24 14:22:00+05:45	1	intersection4	2	4
66	Kalanki	2025-06-24 14:22:00+05:45	4	intersection4	2	1
67	Kalanki	2025-06-24 14:22:00+05:45	1	intersection4	2	2
68	Godawari	2025-06-24 14:22:00+05:45	1	intersection4	2	2
69	Kalanki	2025-06-26 10:42:00+05:45	28	intersection4	2	5
70	Lagankhel	2025-06-26 10:42:00+05:45	1	intersection4	2	5
71	Kalanki	2025-06-26 10:42:00+05:45	3	intersection4	2	6
72	Kalanki	2025-06-26 10:42:00+05:45	3	intersection4	2	17
73	Kalanki	2025-06-26 10:42:00+05:45	2	intersection4	2	12
74	Godawari	2025-06-26 10:42:00+05:45	2	intersection4	2	12
75	Kalanki	2025-06-26 10:42:00+05:45	6	intersection4	2	13
76	Kalanki	2025-06-26 10:42:00+05:45	9	intersection4	2	18
77	Kalanki	2025-06-26 10:42:00+05:45	1	intersection4	2	4
78	Godawari	2025-06-26 10:42:00+05:45	1	intersection4	2	4
79	Kalanki	2025-06-26 10:42:00+05:45	4	intersection4	2	1
80	Kalanki	2025-06-26 10:42:00+05:45	1	intersection4	2	2
81	Kalanki	2025-06-27 07:06:00+05:45	34	intersection4	2	5
82	Lagankhel	2025-06-27 07:06:00+05:45	2	intersection4	2	5
83	Kalanki	2025-06-27 07:06:00+05:45	3	intersection4	2	6
84	Kalanki	2025-06-27 07:06:00+05:45	5	intersection4	2	17
85	Kalanki	2025-06-27 07:06:00+05:45	2	intersection4	2	12
86	Godawari	2025-06-27 07:06:00+05:45	2	intersection4	2	12
87	Kalanki	2025-06-27 07:06:00+05:45	6	intersection4	2	13
88	Kalanki	2025-06-27 07:06:00+05:45	9	intersection4	2	18
89	Kalanki	2025-06-27 07:06:00+05:45	1	intersection4	2	4
90	Godawari	2025-06-27 07:06:00+05:45	1	intersection4	2	4
91	Kalanki	2025-06-27 07:06:00+05:45	4	intersection4	2	1
92	Kalanki	2025-06-27 07:06:00+05:45	1	intersection4	2	2
93	Godawari	2025-06-27 07:06:00+05:45	1	intersection4	2	2
94	Kalanki	2025-06-27 07:07:00+05:45	9	intersection4	2	13
95	Kalanki	2025-06-27 07:07:00+05:45	3	intersection4	2	1
96	Kalanki	2025-06-27 07:07:00+05:45	11	intersection4	2	6
97	Kalanki	2025-06-27 07:07:00+05:45	43	intersection4	2	5
98	Kalanki	2025-06-27 07:07:00+05:45	2	intersection4	2	18
99	Kalanki	2025-06-27 07:07:00+05:45	8	intersection4	2	17
100	Kalanki	2025-06-27 07:07:00+05:45	1	intersection4	2	4
101	Kalanki	2025-06-27 07:08:00+05:45	9	intersection4	2	13
102	Kalanki	2025-06-27 07:08:00+05:45	3	intersection4	2	1
103	Kalanki	2025-06-27 07:08:00+05:45	11	intersection4	2	6
104	Kalanki	2025-06-27 07:08:00+05:45	38	intersection4	2	5
105	Kalanki	2025-06-27 07:08:00+05:45	3	intersection4	2	18
106	Kalanki	2025-06-27 07:08:00+05:45	7	intersection4	2	17
107	Kalanki	2025-06-27 07:08:00+05:45	4	intersection4	2	4
108	Kalanki	2025-06-27 07:08:00+05:45	1	intersection4	2	16
109	Kalanki	2025-06-27 07:08:00+05:45	1	intersection4	2	12
110	Kalanki	2025-06-27 07:09:00+05:45	9	intersection4	2	13
111	Kalanki	2025-06-27 07:09:00+05:45	3	intersection4	2	1
112	Kalanki	2025-06-27 07:09:00+05:45	10	intersection4	2	6
113	Kalanki	2025-06-27 07:09:00+05:45	29	intersection4	2	5
114	Kalanki	2025-06-27 07:09:00+05:45	5	intersection4	2	18
115	Kalanki	2025-06-27 07:09:00+05:45	6	intersection4	2	17
116	Kalanki	2025-06-27 07:09:00+05:45	5	intersection4	2	4
117	Lagankhel	2025-06-27 07:09:00+05:45	2	intersection4	2	4
118	Kalanki	2025-06-27 07:09:00+05:45	5	intersection4	2	12
119	Kalanki	2025-06-27 07:09:00+05:45	3	intersection4	2	8
120	Kalanki	2025-06-27 07:09:00+05:45	1	intersection4	2	2
121	Kalanki	2025-06-27 07:10:00+05:45	8	intersection4	2	13
122	Kalanki	2025-06-27 07:10:00+05:45	3	intersection4	2	1
123	Kalanki	2025-06-27 07:10:00+05:45	9	intersection4	2	6
124	Kalanki	2025-06-27 07:10:00+05:45	29	intersection4	2	5
125	Godawari	2025-06-27 07:10:00+05:45	1	intersection4	2	5
126	Kalanki	2025-06-27 07:10:00+05:45	3	intersection4	2	18
127	Kalanki	2025-06-27 07:10:00+05:45	10	intersection4	2	17
128	Kalanki	2025-06-27 07:10:00+05:45	6	intersection4	2	4
129	Lagankhel	2025-06-27 07:10:00+05:45	1	intersection4	2	4
130	Kalanki	2025-06-27 07:10:00+05:45	10	intersection4	2	12
131	Kalanki	2025-06-27 07:10:00+05:45	3	intersection4	2	8
132	Kalanki	2025-06-27 07:10:00+05:45	1	intersection4	2	2
133	Kalanki	2025-06-27 07:10:00+05:45	2	intersection4	2	16
134	Kalanki	2025-06-27 07:11:00+05:45	16	intersection4	2	13
135	Lagankhel	2025-06-27 07:11:00+05:45	1	intersection4	2	13
136	Kalanki	2025-06-27 07:11:00+05:45	3	intersection4	2	1
137	Kalanki	2025-06-27 07:11:00+05:45	28	intersection4	2	6
138	Lagankhel	2025-06-27 07:11:00+05:45	1	intersection4	2	6
139	Kalanki	2025-06-27 07:11:00+05:45	32	intersection4	2	5
140	Lagankhel	2025-06-27 07:11:00+05:45	2	intersection4	2	5
141	Kalanki	2025-06-27 07:11:00+05:45	4	intersection4	2	18
142	Kalanki	2025-06-27 07:11:00+05:45	8	intersection4	2	17
143	Kalanki	2025-06-27 07:11:00+05:45	6	intersection4	2	4
144	Lagankhel	2025-06-27 07:11:00+05:45	3	intersection4	2	4
145	Kalanki	2025-06-27 07:11:00+05:45	9	intersection4	2	12
146	Godawari	2025-06-27 07:11:00+05:45	1	intersection4	2	12
147	Kalanki	2025-06-27 07:11:00+05:45	2	intersection4	2	8
148	Kalanki	2025-06-27 07:11:00+05:45	2	intersection4	2	16
149	Kalanki	2025-06-27 07:11:00+05:45	1	intersection4	2	2
150	Kalanki	2025-08-03 13:52:00+05:45	51	intersection4	2	5
151	Lagankhel	2025-08-03 13:52:00+05:45	2	intersection4	2	5
152	Kalanki	2025-08-03 13:52:00+05:45	9	intersection4	2	6
153	Kalanki	2025-08-03 13:52:00+05:45	8	intersection4	2	17
154	Kalanki	2025-08-03 13:52:00+05:45	2	intersection4	2	12
155	Godawari	2025-08-03 13:52:00+05:45	2	intersection4	2	12
156	Kalanki	2025-08-03 13:52:00+05:45	6	intersection4	2	13
157	Kalanki	2025-08-03 13:52:00+05:45	9	intersection4	2	18
158	Kalanki	2025-08-03 13:52:00+05:45	2	intersection4	2	4
159	Godawari	2025-08-03 13:52:00+05:45	1	intersection4	2	4
160	Kalanki	2025-08-03 13:52:00+05:45	4	intersection4	2	1
161	Kalanki	2025-08-03 13:52:00+05:45	1	intersection4	2	2
162	Godawari	2025-08-03 13:52:00+05:45	1	intersection4	2	2
163	Kalanki	2025-08-03 13:53:00+05:45	14	intersection4	2	13
164	Kalanki	2025-08-03 13:53:00+05:45	3	intersection4	2	1
165	Kalanki	2025-08-03 13:53:00+05:45	13	intersection4	2	6
166	Kalanki	2025-08-03 13:53:00+05:45	53	intersection4	2	5
167	Kalanki	2025-08-03 13:53:00+05:45	2	intersection4	2	18
168	Kalanki	2025-08-03 13:53:00+05:45	11	intersection4	2	17
169	Kalanki	2025-08-03 13:53:00+05:45	2	intersection4	2	4
170	Kalanki	2025-08-03 13:53:00+05:45	1	intersection4	2	16
171	Kalanki	2025-08-03 13:53:00+05:45	1	intersection4	2	12
172	Kalanki	2025-08-03 13:54:00+05:45	11	intersection4	2	13
173	Kalanki	2025-08-03 13:54:00+05:45	3	intersection4	2	1
174	Kalanki	2025-08-03 13:54:00+05:45	10	intersection4	2	6
175	Kalanki	2025-08-03 13:54:00+05:45	49	intersection4	2	5
176	Godawari	2025-08-03 13:54:00+05:45	1	intersection4	2	5
177	Kalanki	2025-08-03 13:54:00+05:45	6	intersection4	2	18
178	Kalanki	2025-08-03 13:54:00+05:45	9	intersection4	2	17
179	Kalanki	2025-08-03 13:54:00+05:45	6	intersection4	2	4
180	Lagankhel	2025-08-03 13:54:00+05:45	3	intersection4	2	4
181	Kalanki	2025-08-03 13:54:00+05:45	10	intersection4	2	12
182	Kalanki	2025-08-03 13:54:00+05:45	4	intersection4	2	8
183	Kalanki	2025-08-03 13:54:00+05:45	2	intersection4	2	2
184	Kalanki	2025-08-22 18:48:00+05:45	1	intersection4	2	15
185	Kalanki	2025-08-22 18:48:00+05:45	1	intersection4	2	9
186	Kalanki	2025-08-22 18:48:00+05:45	1	intersection4	2	15
187	Kalanki	2025-08-22 18:48:00+05:45	1	intersection4	2	9
188	Kalanki	2025-08-22 18:49:00+05:45	1	intersection4	3	12
189	Kalanki	2025-08-26 16:02:00+05:45	1	intersection4	2	4
190	Kalanki	2025-08-26 16:03:00+05:45	1	intersection4	3	11
191	Kalanki	2025-08-26 17:37:00+05:45	1	intersection4	2	15
192	Kalanki	2025-08-26 17:37:00+05:45	1	intersection4	2	15
193	Godawari	2025-08-26 17:38:00+05:45	1	intersection4	2	15
194	Lagankhel	2025-08-26 17:38:00+05:45	1	intersection4	2	9
195	Godawari	2025-08-26 17:38:00+05:45	1	intersection4	2	15
196	Kalanki	2025-08-26 17:38:00+05:45	1	intersection4	2	6
197	Lagankhel	2025-08-26 17:38:00+05:45	1	intersection4	2	9
198	Kalanki	2025-08-26 17:43:00+05:45	1	intersection4	2	15
199	Kalanki	2025-08-26 17:44:00+05:45	1	intersection4	2	15
201	Kalanki	2025-08-26 17:44:00+05:45	1	intersection4	2	4
200	Godawari	2025-08-26 17:44:00+05:45	1	intersection4	2	4
202	Kalanki	2025-08-26 17:44:00+05:45	1	intersection4	2	4
203	Kalanki	2025-08-26 17:46:00+05:45	1	intersection4	2	15
204	Kalanki	2025-08-26 17:47:00+05:45	1	intersection4	2	4
205	Kalanki	2025-08-26 17:51:00+05:45	1	intersection4	3	4
206	Kalanki	2025-08-26 17:51:00+05:45	1	intersection4	2	15
207	Godawari	2025-08-26 18:00:00+05:45	1	intersection4	3	15
208	Kalanki	2025-08-26 18:00:00+05:45	3	intersection4	3	15
209	Kalanki	2025-08-26 18:01:00+05:45	1	intersection4	3	15
210	Kalanki	2025-08-26 18:00:00+05:45	3	intersection4	2	15
211	Godawari	2025-08-26 18:00:00+05:45	1	intersection4	2	15
212	Godawari	2025-08-26 18:01:00+05:45	2	intersection4	2	15
213	Godawari	2025-08-26 18:02:00+05:45	1	intersection4	2	15
214	Kalanki	2025-08-26 18:06:00+05:45	1	intersection4	2	15
215	Kalanki	2025-08-26 18:07:00+05:45	1	intersection4	3	15
217	Kalanki	2025-08-26 20:22:00+05:45	1	intersection4	2	15
216	Kalanki	2025-08-26 20:22:00+05:45	1	intersection4	2	15
218	Godawari	2025-08-26 20:22:00+05:45	1	intersection4	2	15
219	Godawari	2025-08-26 20:22:00+05:45	1	intersection4	2	15
220	Kalanki	2025-08-26 20:22:00+05:45	1	intersection4	2	12
221	Kalanki	2025-08-26 20:22:00+05:45	1	intersection4	2	7
222	Kalanki	2025-08-26 20:22:00+05:45	1	intersection4	2	7
223	Lagankhel	2025-08-26 20:41:00+05:45	3	intersection4	2	5
224	Kalanki	2025-08-26 20:41:00+05:45	2	intersection4	2	5
225	Lagankhel	2025-08-26 20:41:00+05:45	2	intersection4	2	5
226	Kalanki	2025-08-26 20:41:00+05:45	2	intersection4	2	5
227	Kalanki	2025-08-26 20:41:00+05:45	1	intersection4	2	13
228	Kalanki	2025-08-26 20:41:00+05:45	1	intersection4	2	6
229	Lagankhel	2025-08-26 20:42:00+05:45	1	intersection4	3	5
230	Kalanki	2025-08-26 20:42:00+05:45	3	intersection4	3	5
231	Kalanki	2025-08-26 20:42:00+05:45	1	intersection4	3	6
232	Kalanki	2025-08-26 20:42:00+05:45	6	intersection4	2	5
233	Kalanki	2025-08-26 20:42:00+05:45	4	intersection4	2	6
234	Kalanki	2025-08-26 20:42:00+05:45	1	intersection4	2	13
235	Kalanki	2025-08-26 20:42:00+05:45	3	intersection4	2	5
236	Lagankhel	2025-08-26 20:42:00+05:45	1	intersection4	2	5
237	Kalanki	2025-08-26 20:42:00+05:45	3	intersection4	2	6
238	Kalanki	2025-08-26 20:42:00+05:45	1	intersection4	2	2
239	Kalanki	2025-08-26 20:42:00+05:45	2	intersection4	2	13
240	Kalanki	2025-08-26 20:43:00+05:45	2	intersection4	2	6
241	Kalanki	2025-08-26 20:43:00+05:45	13	intersection4	2	5
242	Lagankhel	2025-08-26 20:43:00+05:45	1	intersection4	2	5
243	Kalanki	2025-08-26 20:43:00+05:45	3	intersection4	2	13
244	Lagankhel	2025-08-26 20:43:00+05:45	1	intersection4	2	13
245	Kalanki	2025-08-26 20:43:00+05:45	10	intersection4	2	5
246	Lagankhel	2025-08-26 20:43:00+05:45	2	intersection4	2	5
247	Kalanki	2025-08-26 20:43:00+05:45	6	intersection4	2	6
248	Kalanki	2025-08-26 20:43:00+05:45	4	intersection4	2	13
249	Lagankhel	2025-08-26 20:43:00+05:45	1	intersection4	2	13
250	Lagankhel	2025-08-27 08:19:00+05:45	1	intersection4	4	12
251	Kalanki	2025-08-27 08:19:00+05:45	2	intersection4	4	12
252	Kalanki	2025-08-28 20:50:00+05:45	4	intersection4	2	5
253	Kalanki	2025-08-28 20:50:00+05:45	3	intersection4	2	5
254	Godawari	2025-08-28 20:50:00+05:45	1	intersection4	2	5
255	Godawari	2025-08-28 20:50:00+05:45	1	intersection4	2	5
256	Kalanki	2025-08-28 20:50:00+05:45	1	intersection4	2	13
257	Kalanki	2025-08-28 20:51:00+05:45	1	intersection4	2	17
258	Kalanki	2025-08-28 20:51:00+05:45	2	intersection4	2	5
259	Godawari	2025-08-28 20:51:00+05:45	1	intersection4	2	5
260	Kalanki	2025-08-28 20:51:00+05:45	1	intersection4	2	6
261	Kalanki	2025-08-28 20:51:00+05:45	3	intersection4	2	5
262	Kalanki	2025-08-29 07:28:00+05:45	1	intersection4	3	5
263	Kalanki	2025-08-29 07:29:00+05:45	1	intersection4	3	9
264	Kalanki	2025-08-29 07:30:00+05:45	1	intersection4	3	9
265	Kalanki	2025-08-29 07:33:00+05:45	1	intersection4	3	9
266	Kalanki	2025-08-29 07:34:00+05:45	1	intersection4	3	12
267	Kalanki	2025-08-29 07:35:00+05:45	1	intersection4	3	12
268	Kalanki	2025-08-29 07:37:00+05:45	2	intersection4	3	12
269	Lagankhel	2025-08-29 07:38:00+05:45	1	intersection4	3	4
270	Kalanki	2025-08-29 07:39:00+05:45	1	intersection4	3	12
271	Kalanki	2025-08-29 07:40:00+05:45	1	intersection4	3	12
272	Kalanki	2025-08-29 07:40:00+05:45	1	intersection4	3	5
273	Kalanki	2025-08-29 07:41:00+05:45	1	intersection4	3	5
274	Kalanki	2025-08-29 07:41:00+05:45	1	intersection4	3	9
275	Kalanki	2025-08-29 07:41:00+05:45	1	intersection4	2	12
276	Kalanki	2025-08-29 07:42:00+05:45	2	intersection4	3	5
277	Godawari	2025-08-29 07:42:00+05:45	1	intersection4	3	5
278	Godawari	2025-08-29 07:42:00+05:45	1	intersection4	2	5
279	Kalanki	2025-08-29 07:42:00+05:45	5	intersection4	2	5
280	Kalanki	2025-08-29 07:42:00+05:45	1	intersection4	2	13
281	Kalanki	2025-08-29 07:42:00+05:45	1	intersection4	2	12
\.


--
-- Data for Name: trafficapp_videosource; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trafficapp_videosource (id, name, path, scenario_id) FROM stdin;
1	IntersectionCam	D:/FinalYearProject/pipeline/videos/intersection4	1
5	collegePhone	rtsp://192.168.7.27:8080/h264_ulaw.sdp	1
4	myPhone	rtsp://192.168.101.7:8080/h264_ulaw.sdp	1
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 88, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 10, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 119, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_results_chordcounter_id_seq', 1, false);


--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_results_groupresult_id_seq', 1, false);


--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_celery_results_taskresult_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 22, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 55, true);


--
-- Name: trafficapp_alertlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_alertlog_id_seq', 1, false);


--
-- Name: trafficapp_alertrule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_alertrule_id_seq', 1, false);


--
-- Name: trafficapp_intersection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_intersection_id_seq', 4, true);


--
-- Name: trafficapp_scenario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_scenario_id_seq', 1, true);


--
-- Name: trafficapp_vehicleclass_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_vehicleclass_id_seq', 18, true);


--
-- Name: trafficapp_vehiclecount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_vehiclecount_id_seq', 281, true);


--
-- Name: trafficapp_videosource_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trafficapp_videosource_id_seq', 5, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_task_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: trafficapp_alertlog trafficapp_alertlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_alertlog
    ADD CONSTRAINT trafficapp_alertlog_pkey PRIMARY KEY (id);


--
-- Name: trafficapp_alertrule trafficapp_alertrule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_alertrule
    ADD CONSTRAINT trafficapp_alertrule_pkey PRIMARY KEY (id);


--
-- Name: trafficapp_intersection trafficapp_intersection_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_intersection
    ADD CONSTRAINT trafficapp_intersection_name_key UNIQUE (name);


--
-- Name: trafficapp_intersection trafficapp_intersection_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_intersection
    ADD CONSTRAINT trafficapp_intersection_pkey PRIMARY KEY (id);


--
-- Name: trafficapp_scenario trafficapp_scenario_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_scenario
    ADD CONSTRAINT trafficapp_scenario_name_key UNIQUE (name);


--
-- Name: trafficapp_scenario trafficapp_scenario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_scenario
    ADD CONSTRAINT trafficapp_scenario_pkey PRIMARY KEY (id);


--
-- Name: trafficapp_vehicleclass trafficapp_vehicleclass_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_vehicleclass
    ADD CONSTRAINT trafficapp_vehicleclass_name_key UNIQUE (name);


--
-- Name: trafficapp_vehicleclass trafficapp_vehicleclass_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_vehicleclass
    ADD CONSTRAINT trafficapp_vehicleclass_pkey PRIMARY KEY (id);


--
-- Name: trafficapp_vehiclecount trafficapp_vehiclecount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_vehiclecount
    ADD CONSTRAINT trafficapp_vehiclecount_pkey PRIMARY KEY (id);


--
-- Name: trafficapp_videosource trafficapp_videosource_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_videosource
    ADD CONSTRAINT trafficapp_videosource_name_key UNIQUE (name);


--
-- Name: trafficapp_videosource trafficapp_videosource_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_videosource
    ADD CONSTRAINT trafficapp_videosource_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cele_date_cr_bd6c1d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_cr_bd6c1d_idx ON public.django_celery_results_groupresult USING btree (date_created);


--
-- Name: django_cele_date_cr_f04a50_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_cr_f04a50_idx ON public.django_celery_results_taskresult USING btree (date_created);


--
-- Name: django_cele_date_do_caae0e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_do_caae0e_idx ON public.django_celery_results_groupresult USING btree (date_done);


--
-- Name: django_cele_date_do_f59aad_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_do_f59aad_idx ON public.django_celery_results_taskresult USING btree (date_done);


--
-- Name: django_cele_periodi_1993cf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_periodi_1993cf_idx ON public.django_celery_results_taskresult USING btree (periodic_task_name);


--
-- Name: django_cele_status_9b6201_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_status_9b6201_idx ON public.django_celery_results_taskresult USING btree (status);


--
-- Name: django_cele_task_na_08aec9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_task_na_08aec9_idx ON public.django_celery_results_taskresult USING btree (task_name);


--
-- Name: django_cele_worker_d54dd8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_worker_d54dd8_idx ON public.django_celery_results_taskresult USING btree (worker);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_celery_results_chordcounter_group_id_1f70858c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_chordcounter_group_id_1f70858c_like ON public.django_celery_results_chordcounter USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_groupresult_group_id_a085f1a9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_groupresult_group_id_a085f1a9_like ON public.django_celery_results_groupresult USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_taskresult_task_id_de0d95bf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_taskresult_task_id_de0d95bf_like ON public.django_celery_results_taskresult USING btree (task_id varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: trafficapp__timesta_7b3536_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp__timesta_7b3536_idx ON public.trafficapp_vehiclecount USING btree ("timestamp", scenario, intersection_id);


--
-- Name: trafficapp_alertlog_rule_id_82b7f195; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_alertlog_rule_id_82b7f195 ON public.trafficapp_alertlog USING btree (rule_id);


--
-- Name: trafficapp_alertrule_created_by_id_da113c41; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_alertrule_created_by_id_da113c41 ON public.trafficapp_alertrule USING btree (created_by_id);


--
-- Name: trafficapp_intersection_name_aa8e267c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_intersection_name_aa8e267c_like ON public.trafficapp_intersection USING btree (name varchar_pattern_ops);


--
-- Name: trafficapp_scenario_name_e6020bbb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_scenario_name_e6020bbb_like ON public.trafficapp_scenario USING btree (name varchar_pattern_ops);


--
-- Name: trafficapp_vehicleclass_name_1b0f6abe_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_vehicleclass_name_1b0f6abe_like ON public.trafficapp_vehicleclass USING btree (name varchar_pattern_ops);


--
-- Name: trafficapp_vehiclecount_intersection_id_0e32513b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_vehiclecount_intersection_id_0e32513b ON public.trafficapp_vehiclecount USING btree (intersection_id);


--
-- Name: trafficapp_vehiclecount_vehicle_class_id_456660d2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_vehiclecount_vehicle_class_id_456660d2 ON public.trafficapp_vehiclecount USING btree (vehicle_class_id);


--
-- Name: trafficapp_videosource_name_981237c2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_videosource_name_981237c2_like ON public.trafficapp_videosource USING btree (name varchar_pattern_ops);


--
-- Name: trafficapp_videosource_scenario_id_cc207b30; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX trafficapp_videosource_scenario_id_cc207b30 ON public.trafficapp_videosource USING btree (scenario_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trafficapp_alertlog trafficapp_alertlog_rule_id_82b7f195_fk_trafficapp_alertrule_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_alertlog
    ADD CONSTRAINT trafficapp_alertlog_rule_id_82b7f195_fk_trafficapp_alertrule_id FOREIGN KEY (rule_id) REFERENCES public.trafficapp_alertrule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trafficapp_alertrule trafficapp_alertrule_created_by_id_da113c41_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_alertrule
    ADD CONSTRAINT trafficapp_alertrule_created_by_id_da113c41_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trafficapp_vehiclecount trafficapp_vehicleco_intersection_id_0e32513b_fk_trafficap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_vehiclecount
    ADD CONSTRAINT trafficapp_vehicleco_intersection_id_0e32513b_fk_trafficap FOREIGN KEY (intersection_id) REFERENCES public.trafficapp_intersection(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trafficapp_vehiclecount trafficapp_vehicleco_vehicle_class_id_456660d2_fk_trafficap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_vehiclecount
    ADD CONSTRAINT trafficapp_vehicleco_vehicle_class_id_456660d2_fk_trafficap FOREIGN KEY (vehicle_class_id) REFERENCES public.trafficapp_vehicleclass(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trafficapp_videosource trafficapp_videosour_scenario_id_cc207b30_fk_trafficap; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trafficapp_videosource
    ADD CONSTRAINT trafficapp_videosour_scenario_id_cc207b30_fk_trafficap FOREIGN KEY (scenario_id) REFERENCES public.trafficapp_scenario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

