# Generated by Django 5.2.1 on 2025-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(help_text='Local folder of MP4s or RTSP URL pointing to camera', max_length=200)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trafficapp.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(help_text='Direction of vehicle flow (e.g., North, South, East, West)', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('count', models.PositiveIntegerField()),
                ('scenario', models.CharField(help_text='Matches Scenario.name', max_length=50)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficapp.intersection')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficapp.vehicleclass')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'scenario', 'intersection'], name='trafficapp__timesta_7b3536_idx')],
            },
        ),
    ]
