# Generated by Django 5.2.1 on 2025-08-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('scenarios', models.JSONField(blank=True, default=list, help_text='List of scenario names (empty = all)')),
                ('directions', models.JSONField(blank=True, default=list, help_text='List of directions (empty = all)')),
                ('vehicle_classes', models.JSONField(blank=True, default=list, help_text='List of vehicle class names (empty = all)')),
                ('rule_type', models.CharField(choices=[('absolute', 'Absolute Threshold'), ('percent_spike', 'Percent Spike vs baseline'), ('sustained', 'Sustained high count')], max_length=32)),
                ('threshold', models.FloatField(default=10, help_text='Meaning depends on rule_type')),
                ('sustained_minutes', models.IntegerField(default=0, help_text="For 'sustained' rule: minutes to satisfy")),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooldown_seconds', models.IntegerField(default=300, help_text='Do not re-alert same rule within this many seconds')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(blank=True, max_length=150, null=True)),
                ('direction', models.CharField(blank=True, max_length=64, null=True)),
                ('vehicle_class', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('sent_emails', models.TextField(blank=True)),
                ('webhook_status', models.CharField(blank=True, max_length=256)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trafficapp.alertrule')),
            ],
        ),
    ]
